config/routes.rb
Rails.application.routes.draw do
  resources :lookups, only: %i[ show create ]

  # health status that returns 200 if the app boots with no exceptions
  # can be used to verify the app is live
  get 'up' => 'rails/health#show', as: :rails_health_check

  # defines the root path route ('/')
  root 'public#index'
end

app/models/lookup.rb
class Lookup < ApplicationRecord
	has_many :forecasts

	def with_scale(attribute)
		return "#{self[attribute]}℉" if scale.eql? 'fahrenheit'
		"#{self[attribute]}℃"
	end
end

app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  before_action :set_lookup, only: %i[ show edit update destroy ]
  before_action :set_zip_code_from_query, only: %i[ create ]
  before_action :set_lookup_from_zip_code, only: %i[ create ]
  before_action :query_weather_api, only: %i[ create ]

  # GET /lookups or /lookups.json
  def index
    @lookups = Lookup.all
  end

  # GET /lookups/1 or /lookups/1.json
  def show
  end

  # GET /lookups/new
  def new
    @lookup = Lookup.new
  end

  # GET /lookups/1/edit
  def edit
  end

  # POST /lookups or /lookups.json
  def create
    # checks if we already have a recently cached lookup to display
    if @lookup.present?
      respond_to do |format|
        format.html { redirect_to lookup_url(@lookup), notice: "These weather conditions were last updated #{helpers.time_ago_in_words(@lookup.cached_at)} ago" }
        format.json { render :show, status: :ok, location: @lookup }
      end
    else
      @lookup = Lookup.new(lookup_params)

      respond_to do |format|
        if @lookup.save
          format.html { redirect_to lookup_url(@lookup) }
          format.json { render :show, status: :created, location: @lookup }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @lookup.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /lookups/1 or /lookups/1.json
  def update
    respond_to do |format|
      if @lookup.update(lookup_params)
        format.html { redirect_to lookup_url(@lookup), notice: "Lookup was successfully updated." }
        format.json { render :show, status: :ok, location: @lookup }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lookups/1 or /lookups/1.json
  def destroy
    @lookup.destroy!

    respond_to do |format|
      format.html { redirect_to lookups_url, notice: "Lookup was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lookup
      @lookup = Lookup.find(params[:id])
    end

    def set_zip_code_from_query
      # skip this and move on if we've already got a zip code
      unless helpers.query_is_zip_code(params[:query])
        # tries to extract the zip code directly from the address
        params[:query] = helpers.extract_zip_code_params_from_query(params[:query])

        unless helpers.query_is_zip_code(params[:query])
          # tries to use reverse geocoding to look up the zip code
          params[:query] = helpers.lookup_zip_code_params_from_query(params[:query])

          unless helpers.query_is_zip_code(params[:query])
            # looks like all our efforts failed and we couldn't find a zip code
            respond_to do |format|
              format.html { redirect_to root_path, notice: "Sorry, but we couldn't make sense of that address. Try again?" }
              format.json { render json: @lookup.errors, status: :unprocessable_entity }
            end
          end
        end
      end
    end

    def set_lookup_from_zip_code
      zip_code = params[:query]
      scale = params[:scale]

      @lookup = Lookup.find_by("zip_code = ? AND scale = ? AND cached_at > ?", zip_code, scale, 30.minutes.ago)
    end

    # Uses WeatherAPI.com to lookup weather based on the search query
    def query_weather_api
      # skips if we already have a recently cached lookup to display
      unless @lookup.present?
        zip_code = params[:query]
        scale = params[:scale]

        params[:lookup] = helpers.supply_lookup_params_from_weather_query(zip_code, scale)
      end
    end

    # Only allow a list of trusted parameters through.
    def lookup_params
      params.require(:lookup).permit(:zip_code, :cached_at, :scale, :temperature, :high, :low, :condition, :icon)
    end
end

app/helpers/lookups_helper.rb
module LookupsHelper
	GEOCODING_API_BASE_URL = 'https://geocode.maps.co/search?'.freeze
	GEOCODING_API_KEY = Figaro.env.geocoding_api_key.freeze

	WEATHER_API_BASE_URL = 'https://api.weatherapi.com/v1/forecast.json?'.freeze
	WEATHER_API_KEY = Figaro.env.weather_api_key.freeze

	GEOCODING_EXTRACT_ZIP_CODE_REGEX = /^.+, (?<zip_code>\d{5}), United States$/
	ZIP_CODE_REGEX = /^\d{5}$/
	ZIP_CODE_PARTIAL_REGEX = /.*(\d{5})/

	def query_is_zip_code(query)
		ZIP_CODE_REGEX.match(query).present?
	end

	def query_contains_zip_code(query)
		ZIP_CODE_PARTIAL_REGEX.match(query).present?
	end

	def extract_zip_code_params_from_query(query)
		# can't do anything here because there's no zip code in the query
		return query unless query_contains_zip_code(query)

		# returns the last 5-digit match in case there's a long street number
		ZIP_CODE_PARTIAL_REGEX.match(query)[-1]
	end

	def lookup_zip_code_params_from_query(query)
		# can't do anything, so just return the OG query and hope for the best!
		return query unless Figaro.env.geocoding_api_key?

		# let's goooooooooooo
		url = "#{GEOCODING_API_BASE_URL}api_key=#{GEOCODING_API_KEY}&q=#{query}"
		response = HTTParty.get(url)

		return query unless response.code == 200

		data = JSON.parse(response.body)

		if data.present?
			match_data = GEOCODING_EXTRACT_ZIP_CODE_REGEX.match(data[0]['display_name'])
			return match_data['zip_code'] if match_data.present? && query_is_zip_code(match_data['zip_code'])
		end

		query
	end

	def supply_lookup_params_from_weather_query(zip_code, scale)
		url = "#{WEATHER_API_BASE_URL}key=#{WEATHER_API_KEY}&q=#{zip_code}&days=7&aqi=no&alerts=no"
		response = HTTParty.get(url)

		return {} unless response.code == 200

		params = {}
		params[:zip_code] = zip_code
		params[:cached_at] = Time.now.to_s
		params[:scale] = scale

		data = JSON.parse(response.body)

		# checks if we should store results in Fahrenheit or Celsius
		if scale.eql? 'fahrenheit'
			params[:temperature] = data['current']['temp_f']
			params[:high] = data['forecast']['forecastday'][0]['day']['maxtemp_f']
			params[:low] = data['forecast']['forecastday'][0]['day']['mintemp_f']
		else
			params[:temperature] = data['current']['temp_c']
			params[:high] = data['forecast']['forecastday'][0]['day']['maxtemp_c']
			params[:low] = data['forecast']['forecastday'][0]['day']['mintemp_c']
		end

		params[:condition] = data['current']['condition']['text']
		params[:icon] = data['current']['condition']['icon']

		params
	end
end

app/views/lookups/_form.html.erb
<%= form_with(model: lookup, class: "contents") do |form| %>
  <% if lookup.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(lookup.errors.count, "error") %> prohibited this lookup from being saved:</h2>

      <ul>
        <% lookup.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cached_at %>
    <%= form.datetime_field :cached_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :scale %>
    <%= form.text_field :scale, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :temperature %>
    <%= form.text_field :temperature, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :high %>
    <%= form.text_field :high, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :low %>
    <%= form.text_field :low, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :condition %>
    <%= form.text_field :condition, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :icon %>
    <%= form.text_field :icon, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/lookups/_lookup.html.erb
<div class="mx-auto my-8" id="<%= dom_id lookup %>">
  <h2 class="font-bold text-2xl">Current Weather for <%= lookup.zip_code %></h2>
  <img class="float-left mb-96" src="<%= lookup.icon %>" />

  <p class="my-4">
    <strong>Current Temperature:</strong> <%= lookup.with_scale(:temperature) %>
    <br>
    <strong>Conditions:</strong> <%= lookup.condition %>
  </p>

  <p class="my-4">
    <strong>High:</strong> <%= lookup.with_scale(:high) %> /
    <strong>Low:</strong> <%= lookup.with_scale(:low) %>
  </p>
</div>

app/views/lookups/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing lookup</h1>

  <%= render "form", lookup: @lookup %>

  <%= link_to "Show this lookup", @lookup, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to lookups", lookups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/lookups/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Lookups</h1>
    <%= link_to "New lookup", new_lookup_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="lookups" class="min-w-full">
    <%= render @lookups %>
  </div>
</div>

app/views/lookups/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New lookup</h1>

  <%= render "form", lookup: @lookup %>

  <%= link_to "Back to lookups", lookups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/lookups/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl text-blue-500"><a href="/">WeatherBear</a></h1>
  <p class="italic">Just the bare essentials of a daily forecast</p>
  <hr>

  <div class="mx-auto my-8">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
  </div>

  <%= render @lookup %>

  <div class="mt-16">
    <p class="font-bold text-right">Hans (the bear) says:</p>
    <p class="text-right" data-controller="punchline"></p>
    <img class="mt-4 float-right" src="/assets/hans-the-bear.jpg" />
  </div>
</div>